// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Jeepify

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void AnimNavIn_Animation(lv_obj_t * TargetObject, int delay);
void AnimNavOut_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_ScrSingle
void ui_ScrSingle_screen_init(void);
void ui_event_ScrSingle(lv_event_t * e);
lv_obj_t * ui_ScrSingle;
lv_obj_t * ui_Image9;
lv_obj_t * ui_LblSinglePeer;
lv_obj_t * ui_LblSingleValue;
lv_obj_t * ui_LblSinglePeriph;
void ui_event_BtnNavIn(lv_event_t * e);
lv_obj_t * ui_BtnNavIn;
lv_obj_t * ui_NavPanel;
void ui_event_BtnNavMenu(lv_event_t * e);
lv_obj_t * ui_BtnNavMenu;
lv_obj_t * ui_LblBtnNavMenu;
void ui_event_BtnNavSingle(lv_event_t * e);
lv_obj_t * ui_BtnNavSingle;
void ui_event_BtnNavMulti(lv_event_t * e);
lv_obj_t * ui_BtnNavMulti;
void ui_event_BtnNavSwitch(lv_event_t * e);
lv_obj_t * ui_BtnNavSwitch;
void ui_event_BtnNavSettings(lv_event_t * e);
lv_obj_t * ui_BtnNavSettings;
void ui_event_BtnSingleNext(lv_event_t * e);
lv_obj_t * ui_BtnSingleNext;
void ui_event_BtnSingleNext1(lv_event_t * e);
lv_obj_t * ui_BtnSingleNext1;


// SCREEN: ui_ScrPeers
void ui_ScrPeers_screen_init(void);
void ui_event_ScrPeers(lv_event_t * e);
lv_obj_t * ui_ScrPeers;
void ui_event_RollerPeers1(lv_event_t * e);
lv_obj_t * ui_RollerPeers1;
lv_obj_t * ui_LabelPeersName;


// SCREEN: ui_ScrJSON
void ui_ScrJSON_screen_init(void);
void ui_event_ScrJSON(lv_event_t * e);
lv_obj_t * ui_ScrJSON;
lv_obj_t * ui_TxtJSON1;
lv_obj_t * ui_LblJSON2;


// SCREEN: ui_ScrPeer
void ui_ScrPeer_screen_init(void);
void ui_event_ScrPeer(lv_event_t * e);
lv_obj_t * ui_ScrPeer;
lv_obj_t * ui_ImgPeerType;
lv_obj_t * ui_LblPeerTypeLbl;
lv_obj_t * ui_LblPeerName;
void ui_event_BtnPeer1(lv_event_t * e);
lv_obj_t * ui_BtnPeer1;
void ui_event_BtnPeer1Lbl(lv_event_t * e);
lv_obj_t * ui_BtnPeer1Lbl;
void ui_event_BtnPeer2(lv_event_t * e);
lv_obj_t * ui_BtnPeer2;
lv_obj_t * ui_BtnPeer2Lbl1;
void ui_event_BtnPeer3(lv_event_t * e);
lv_obj_t * ui_BtnPeer3;
lv_obj_t * ui_BtnPeer3Lbl1;
void ui_event_BtnPeer4(lv_event_t * e);
lv_obj_t * ui_BtnPeer4;
lv_obj_t * ui_BtnPeer4Lbl1;
void ui_event_BtnPeer5(lv_event_t * e);
lv_obj_t * ui_BtnPeer5;
lv_obj_t * ui_BtnPeer5Lbl1;
void ui_event_BtnPeer6(lv_event_t * e);
lv_obj_t * ui_BtnPeer6;
lv_obj_t * ui_BtnPeer6Lbl1;
void ui_event_BtnPeer7(lv_event_t * e);
lv_obj_t * ui_BtnPeer7;
void ui_event_BtnPeer7Lbl1(lv_event_t * e);
lv_obj_t * ui_BtnPeer7Lbl1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
void ui_event_BtnPeerNext(lv_event_t * e);
lv_obj_t * ui_BtnPeerNext;
void ui_event_BtnPeerLast(lv_event_t * e);
lv_obj_t * ui_BtnPeerLast;


// SCREEN: ui_ScrEichen
void ui_ScrEichen_screen_init(void);
lv_obj_t * ui_ScrEichen;
lv_obj_t * ui_Label1;
void ui_event_BtnEichenStart(lv_event_t * e);
lv_obj_t * ui_BtnEichenStart;
lv_obj_t * ui_BtnPeer4Lbl3;
lv_obj_t * ui_LblEichenPeer;


// SCREEN: ui_ScrVolt
void ui_ScrVolt_screen_init(void);
void ui_event_ScrVolt(lv_event_t * e);
lv_obj_t * ui_ScrVolt;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_TxtVolt;
void ui_event_LblVoltPeer(lv_event_t * e);
lv_obj_t * ui_LblVoltPeer;


// SCREEN: ui_ScrPeriph
void ui_ScrPeriph_screen_init(void);
void ui_event_ScrPeriph(lv_event_t * e);
lv_obj_t * ui_ScrPeriph;
lv_obj_t * ui_ImgPeerChoice;
lv_obj_t * ui_LblPeriphChoicePeer;
lv_obj_t * ui_LblPeriphChoiceType;
lv_obj_t * ui_LblPeriphChoiceOnline;
lv_obj_t * ui_LblPeriphChoicePeriph;
void ui_event_BtnPeriphNext(lv_event_t * e);
lv_obj_t * ui_BtnPeriphNext;
void ui_event_BtnPeriphLast(lv_event_t * e);
lv_obj_t * ui_BtnPeriphLast;


// SCREEN: ui_ScrMulti
void ui_ScrMulti_screen_init(void);
void ui_event_ScrMulti(lv_event_t * e);
lv_obj_t * ui_ScrMulti;
lv_obj_t * ui_LblMultiScreenName;
void ui_event_ButtonMulti1(lv_event_t * e);
lv_obj_t * ui_ButtonMulti1;
lv_obj_t * ui_Label6;
void ui_event_ButtonMulti2(lv_event_t * e);
lv_obj_t * ui_ButtonMulti2;
lv_obj_t * ui_Label2;
void ui_event_ButtonMulti3(lv_event_t * e);
lv_obj_t * ui_ButtonMulti3;
lv_obj_t * ui_Label3;
void ui_event_ButtonMulti4(lv_event_t * e);
lv_obj_t * ui_ButtonMulti4;
lv_obj_t * ui_Label4;
void ui_event_BtnMultiLast(lv_event_t * e);
lv_obj_t * ui_BtnMultiLast;
void ui_event_BtnMultiNext(lv_event_t * e);
lv_obj_t * ui_BtnMultiNext;


// SCREEN: ui_ScrSwitch
void ui_ScrSwitch_screen_init(void);
void ui_event_ScrSwitch(lv_event_t * e);
lv_obj_t * ui_ScrSwitch;
lv_obj_t * ui_SpinnerSwitch;
void ui_event_ImgButtonSwitch(lv_event_t * e);
lv_obj_t * ui_ImgButtonSwitch;
lv_obj_t * ui_LblSwitchPeriph;
lv_obj_t * ui_LblSwitchAmp;
lv_obj_t * ui_LblSwitchPeer;
void ui_event_BtnSwitchNext(lv_event_t * e);
lv_obj_t * ui_BtnSwitchNext;
void ui_event_BtnSwitchLast(lv_event_t * e);
lv_obj_t * ui_BtnSwitchLast;
void ui_event_ImgButtonSwitch1(lv_event_t * e);
lv_obj_t * ui_ImgButtonSwitch1;
void ui_event_ImgButtonSwitch2(lv_event_t * e);
lv_obj_t * ui_ImgButtonSwitch2;
void ui_event_ImgButtonSwitch3(lv_event_t * e);
lv_obj_t * ui_ImgButtonSwitch3;


// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
void ui_event_ScrSettings(lv_event_t * e);
lv_obj_t * ui_ScrSettings;
void ui_event_BtnSet1(lv_event_t * e);
lv_obj_t * ui_BtnSet1;
lv_obj_t * ui_BtnSet1Lbl1;
void ui_event_BtnSet2(lv_event_t * e);
lv_obj_t * ui_BtnSet2;
lv_obj_t * ui_BtnSet2Lbl;
void ui_event_BtnSet3(lv_event_t * e);
lv_obj_t * ui_BtnSet3;
lv_obj_t * ui_BtnSet3Lbl3;
void ui_event_BtnSet4(lv_event_t * e);
lv_obj_t * ui_BtnSet4;
lv_obj_t * ui_BtnSet3Lbl1;
void ui_event_BtnSet5(lv_event_t * e);
lv_obj_t * ui_BtnSet5;
lv_obj_t * ui_BtnSet5Lbl;
void ui_event_BtnSet6(lv_event_t * e);
lv_obj_t * ui_BtnSet6;
lv_obj_t * ui_BtnSet3Lbl2;
void ui_event_BtnSet7(lv_event_t * e);
lv_obj_t * ui_BtnSet7;
lv_obj_t * ui_BtnSet7Lbl;
void ui_event_BtnSet8(lv_event_t * e);
lv_obj_t * ui_BtnSet8;
lv_obj_t * ui_BtnSet7Lbl1;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_ansgarmodule_[1] = {&ui_img_ansgarmodule_4_png};
const lv_img_dsc_t * ui_imgset_683550019[1] = {&ui_img_694597045};
const lv_img_dsc_t * ui_imgset_643149428[1] = {&ui_img_315456014};
const lv_img_dsc_t * ui_imgset_1689556857[1] = {&ui_img_1714525409};
const lv_img_dsc_t * ui_imgset_236161557[1] = {&ui_img_1464630232};
const lv_img_dsc_t * ui_imgset_857919995[1] = {&ui_img_1562670045};
const lv_img_dsc_t * ui_imgset_25820555[1] = {&ui_img_587468927};
const lv_img_dsc_t * ui_imgset_g[1] = {&ui_img_g3_png};
const lv_img_dsc_t * ui_imgset_1573734952[1] = {&ui_img_1156157770};
const lv_img_dsc_t * ui_imgset_horstrelais[1] = {&ui_img_horstrelais2_png};
const lv_img_dsc_t * ui_imgset_menubtn[2] = {&ui_img_menubtn1_png, &ui_img_menubtn2_png};
const lv_img_dsc_t * ui_imgset_1017471526[1] = {&ui_img_546008632};
const lv_img_dsc_t * ui_imgset_1265058017[1] = {&ui_img_1769637049};
const lv_img_dsc_t * ui_imgset_883720742[1] = {&ui_img_215445388};
const lv_img_dsc_t * ui_imgset_1212679602[1] = {&ui_img_44778140};
const lv_img_dsc_t * ui_imgset_162360510[1] = {&ui_img_1891462800};
const lv_img_dsc_t * ui_imgset_46625239[1] = {&ui_img_410295087};
const lv_img_dsc_t * ui_imgset_1014533431[1] = {&ui_img_1640860301};
const lv_img_dsc_t * ui_imgset_201250811[1] = {&ui_img_888658411};
const lv_img_dsc_t * ui_imgset_1737837525[1] = {&ui_img_743505413};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void AnimNavIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -280, -205);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void AnimNavOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -205, -280);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScrSingle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Single_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Single_Last(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Single_Prepare(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Ui_Single_Leave(e);
    }
}
void ui_event_BtnNavIn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        AnimNavIn_Animation(ui_NavPanel, 0);
        _ui_flag_modify(ui_BtnNavIn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BtnNavMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_BtnNavIn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        AnimNavOut_Animation(ui_NavPanel, 0);
    }
}
void ui_event_BtnNavSingle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrSingle, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrSingle_screen_init);
    }
}
void ui_event_BtnNavMulti(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMulti, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrMulti_screen_init);
    }
}
void ui_event_BtnNavSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrSwitch, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrSwitch_screen_init);
    }
}
void ui_event_BtnNavSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrSettings_screen_init);
    }
}
void ui_event_BtnSingleNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Single_Prev(e);
    }
}
void ui_event_BtnSingleNext1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Single_Next(e);
    }
}
void ui_event_ScrPeers(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Peers_Prepare(e);
    }
}
void ui_event_RollerPeers1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Peers_Selected(e);
    }
}
void ui_event_ScrJSON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_JSON_Prepare(e);
    }
}
void ui_event_ScrPeer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Peer_Loaded(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Peer_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Peer_Last(e);
    }
}
void ui_event_BtnPeer1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}
void ui_event_BtnPeer1Lbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}
void ui_event_BtnPeer2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Peer_Reset(e);
    }
}
void ui_event_BtnPeer3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_ToggleSleep(e);
    }
}
void ui_event_BtnPeer4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrEichen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrEichen_screen_init);
    }
}
void ui_event_BtnPeer5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrVolt, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrVolt_screen_init);
    }
}
void ui_event_BtnPeer6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_ToggleDemo(e);
    }
}
void ui_event_BtnPeer7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Peer_Delete(e);
    }
}
void ui_event_BtnPeer7Lbl1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}
void ui_event_BtnPeerNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Next(e);
    }
}
void ui_event_BtnPeerLast(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Prev(e);
    }
}
void ui_event_BtnEichenStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Eichen_Start(e);
    }
}
void ui_event_ScrVolt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Volt_Prepare(e);
    }
}
void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        Ui_Volt_Start(e);
    }
}
void ui_event_LblVoltPeer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        (e);
    }
}
void ui_event_ScrPeriph(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_PeriphChoice_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_PeriphChoice_Last(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_PeriphChoice_Click(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Periph_Choice_Loaded(e);
    }
}
void ui_event_BtnPeriphNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_PeriphChoice_Next(e);
    }
}
void ui_event_BtnPeriphLast(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_PeriphChoice_Last(e);
    }
}
void ui_event_ScrMulti(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Multi_Loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Ui_Multi_Unload(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Multi_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Multi_Prev(e);
    }
}
void ui_event_ButtonMulti1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel1(e);
    }
}
void ui_event_ButtonMulti2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel2(e);
    }
}
void ui_event_ButtonMulti3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel3(e);
    }
}
void ui_event_ButtonMulti4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel4(e);
    }
}
void ui_event_BtnMultiLast(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Prev(e);
    }
}
void ui_event_BtnMultiNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Next(e);
    }
}
void ui_event_ScrSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Switch_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Switch_Prev(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Switch_Loaded(e);
    }
}
void ui_event_ImgButtonSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Long(e);
    }
}
void ui_event_BtnSwitchNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Next(e);
    }
}
void ui_event_BtnSwitchLast(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Prev(e);
    }
}
void ui_event_ImgButtonSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Long(e);
    }
}
void ui_event_ImgButtonSwitch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Long(e);
    }
}
void ui_event_ImgButtonSwitch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Switch_Long(e);
    }
}
void ui_event_ScrSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Set_Prepare(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Ui_Set_Leave(e);
    }
}
void ui_event_BtnSet1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_WebSvr(e);
    }
}
void ui_event_BtnSet2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_TogglePair(e);
    }
}
void ui_event_BtnSet3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_Restart(e);
    }
}
void ui_event_BtnSet4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Set_Reset(e);
    }
}
void ui_event_BtnSet5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrPeers, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrPeers_screen_init);
    }
}
void ui_event_BtnSet6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrJSON, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrJSON_screen_init);
    }
}
void ui_event_BtnSet7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_ToggleDebug(e);
    }
}
void ui_event_BtnSet8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_SavePeers(e);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Init_Custom(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScrSingle_screen_init();
    ui_ScrPeers_screen_init();
    ui_ScrJSON_screen_init();
    ui_ScrPeer_screen_init();
    ui_ScrEichen_screen_init();
    ui_ScrVolt_screen_init();
    ui_ScrPeriph_screen_init();
    ui_ScrMulti_screen_init();
    ui_ScrSwitch_screen_init();
    ui_ScrSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_ScrSingle);
}
