// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _JEEPIFY_UI_H
#define _JEEPIFY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void AnimNavIn_Animation(lv_obj_t * TargetObject, int delay);
void AnimNavOut_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScrSingle
void ui_ScrSingle_screen_init(void);
void ui_event_ScrSingle(lv_event_t * e);
extern lv_obj_t * ui_ScrSingle;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_LblSinglePeer;
extern lv_obj_t * ui_LblSingleValue;
extern lv_obj_t * ui_LblSinglePeriph;
void ui_event_BtnNavIn(lv_event_t * e);
extern lv_obj_t * ui_BtnNavIn;
extern lv_obj_t * ui_NavPanel;
void ui_event_BtnNavMenu(lv_event_t * e);
extern lv_obj_t * ui_BtnNavMenu;
extern lv_obj_t * ui_LblBtnNavMenu;
void ui_event_BtnNavSingle(lv_event_t * e);
extern lv_obj_t * ui_BtnNavSingle;
void ui_event_BtnNavMulti(lv_event_t * e);
extern lv_obj_t * ui_BtnNavMulti;
void ui_event_BtnNavSwitch(lv_event_t * e);
extern lv_obj_t * ui_BtnNavSwitch;
void ui_event_BtnNavSettings(lv_event_t * e);
extern lv_obj_t * ui_BtnNavSettings;
void ui_event_BtnSingleNext(lv_event_t * e);
extern lv_obj_t * ui_BtnSingleNext;
void ui_event_BtnSingleNext1(lv_event_t * e);
extern lv_obj_t * ui_BtnSingleNext1;
// SCREEN: ui_ScrPeers
void ui_ScrPeers_screen_init(void);
void ui_event_ScrPeers(lv_event_t * e);
extern lv_obj_t * ui_ScrPeers;
void ui_event_RollerPeers1(lv_event_t * e);
extern lv_obj_t * ui_RollerPeers1;
extern lv_obj_t * ui_LabelPeersName;
// SCREEN: ui_ScrJSON
void ui_ScrJSON_screen_init(void);
void ui_event_ScrJSON(lv_event_t * e);
extern lv_obj_t * ui_ScrJSON;
extern lv_obj_t * ui_TxtJSON1;
extern lv_obj_t * ui_LblJSON2;
// SCREEN: ui_ScrPeer
void ui_ScrPeer_screen_init(void);
void ui_event_ScrPeer(lv_event_t * e);
extern lv_obj_t * ui_ScrPeer;
extern lv_obj_t * ui_ImgPeerType;
extern lv_obj_t * ui_LblPeerTypeLbl;
extern lv_obj_t * ui_LblPeerName;
void ui_event_BtnPeer1(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer1;
void ui_event_BtnPeer1Lbl(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer1Lbl;
void ui_event_BtnPeer2(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer2;
extern lv_obj_t * ui_BtnPeer2Lbl1;
void ui_event_BtnPeer3(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer3;
extern lv_obj_t * ui_BtnPeer3Lbl1;
void ui_event_BtnPeer4(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer4;
extern lv_obj_t * ui_BtnPeer4Lbl1;
void ui_event_BtnPeer5(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer5;
extern lv_obj_t * ui_BtnPeer5Lbl1;
void ui_event_BtnPeer6(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer6;
extern lv_obj_t * ui_BtnPeer6Lbl1;
void ui_event_BtnPeer7(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer7;
void ui_event_BtnPeer7Lbl1(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer7Lbl1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
void ui_event_BtnPeerNext(lv_event_t * e);
extern lv_obj_t * ui_BtnPeerNext;
void ui_event_BtnPeerLast(lv_event_t * e);
extern lv_obj_t * ui_BtnPeerLast;
// SCREEN: ui_ScrEichen
void ui_ScrEichen_screen_init(void);
extern lv_obj_t * ui_ScrEichen;
extern lv_obj_t * ui_Label1;
void ui_event_BtnEichenStart(lv_event_t * e);
extern lv_obj_t * ui_BtnEichenStart;
extern lv_obj_t * ui_BtnPeer4Lbl3;
extern lv_obj_t * ui_LblEichenPeer;
// SCREEN: ui_ScrVolt
void ui_ScrVolt_screen_init(void);
void ui_event_ScrVolt(lv_event_t * e);
extern lv_obj_t * ui_ScrVolt;
void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_TxtVolt;
void ui_event_LblVoltPeer(lv_event_t * e);
extern lv_obj_t * ui_LblVoltPeer;
// SCREEN: ui_ScrPeriph
void ui_ScrPeriph_screen_init(void);
void ui_event_ScrPeriph(lv_event_t * e);
extern lv_obj_t * ui_ScrPeriph;
extern lv_obj_t * ui_ImgPeerChoice;
extern lv_obj_t * ui_LblPeriphChoicePeer;
extern lv_obj_t * ui_LblPeriphChoiceType;
extern lv_obj_t * ui_LblPeriphChoiceOnline;
extern lv_obj_t * ui_LblPeriphChoicePeriph;
void ui_event_BtnPeriphNext(lv_event_t * e);
extern lv_obj_t * ui_BtnPeriphNext;
void ui_event_BtnPeriphLast(lv_event_t * e);
extern lv_obj_t * ui_BtnPeriphLast;
// SCREEN: ui_ScrMulti
void ui_ScrMulti_screen_init(void);
void ui_event_ScrMulti(lv_event_t * e);
extern lv_obj_t * ui_ScrMulti;
extern lv_obj_t * ui_LblMultiScreenName;
void ui_event_ButtonMulti1(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti1;
extern lv_obj_t * ui_Label6;
void ui_event_ButtonMulti2(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti2;
extern lv_obj_t * ui_Label2;
void ui_event_ButtonMulti3(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti3;
extern lv_obj_t * ui_Label3;
void ui_event_ButtonMulti4(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti4;
extern lv_obj_t * ui_Label4;
void ui_event_BtnMultiLast(lv_event_t * e);
extern lv_obj_t * ui_BtnMultiLast;
void ui_event_BtnMultiNext(lv_event_t * e);
extern lv_obj_t * ui_BtnMultiNext;
// SCREEN: ui_ScrSwitch
void ui_ScrSwitch_screen_init(void);
void ui_event_ScrSwitch(lv_event_t * e);
extern lv_obj_t * ui_ScrSwitch;
extern lv_obj_t * ui_LblSwitchPeer;
void ui_event_BtnSwitchNext(lv_event_t * e);
extern lv_obj_t * ui_BtnSwitchNext;
void ui_event_BtnSwitchLast(lv_event_t * e);
extern lv_obj_t * ui_BtnSwitchLast;
// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
void ui_event_ScrSettings(lv_event_t * e);
extern lv_obj_t * ui_ScrSettings;
void ui_event_BtnSet1(lv_event_t * e);
extern lv_obj_t * ui_BtnSet1;
extern lv_obj_t * ui_BtnSet1Lbl1;
void ui_event_BtnSet2(lv_event_t * e);
extern lv_obj_t * ui_BtnSet2;
extern lv_obj_t * ui_BtnSet2Lbl;
void ui_event_BtnSet3(lv_event_t * e);
extern lv_obj_t * ui_BtnSet3;
extern lv_obj_t * ui_BtnSet3Lbl3;
void ui_event_BtnSet4(lv_event_t * e);
extern lv_obj_t * ui_BtnSet4;
extern lv_obj_t * ui_BtnSet3Lbl1;
void ui_event_BtnSet5(lv_event_t * e);
extern lv_obj_t * ui_BtnSet5;
extern lv_obj_t * ui_BtnSet5Lbl;
void ui_event_BtnSet6(lv_event_t * e);
extern lv_obj_t * ui_BtnSet6;
extern lv_obj_t * ui_BtnSet3Lbl2;
void ui_event_BtnSet7(lv_event_t * e);
extern lv_obj_t * ui_BtnSet7;
extern lv_obj_t * ui_BtnSet7Lbl;
void ui_event_BtnSet8(lv_event_t * e);
extern lv_obj_t * ui_BtnSet8;
extern lv_obj_t * ui_BtnSet7Lbl1;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1464630232);    // assets/BG-Gauge2.png
LV_IMG_DECLARE(ui_img_1714525409);    // assets/bezel-silver-orig-300.png
LV_IMG_DECLARE(ui_img_g3_png);    // assets/g3.png
LV_IMG_DECLARE(ui_img_1156157770);    // assets/gauge-50.png
LV_IMG_DECLARE(ui_img_546008632);    // assets/multi-50.png
LV_IMG_DECLARE(ui_img_215445388);    // assets/power-50.png
LV_IMG_DECLARE(ui_img_44778140);    // assets/settings-50.png
LV_IMG_DECLARE(ui_img_694597045);    // assets/arrow_down-50.png
LV_IMG_DECLARE(ui_img_315456014);    // assets/arrow_up-50.png
LV_IMG_DECLARE(ui_img_ansgarmodule_4_png);    // assets/AnsgarModule_4.png
LV_IMG_DECLARE(ui_img_friedermodule_disp_png);    // assets/FriederModule_Disp.png
LV_IMG_DECLARE(ui_img_horstrelais2_png);    // assets/HorstRelais2.png
LV_IMG_DECLARE(ui_img_1769637049);    // assets/PeterRelais-1.png
LV_IMG_DECLARE(ui_img_rolfmodule_round_png);    // assets/RolfModule_round.png
LV_IMG_DECLARE(ui_img_menubtn2_png);    // assets/MenuBtn2.png
LV_IMG_DECLARE(ui_img_1562670045);    // assets/Btn-small-off-100.png
LV_IMG_DECLARE(ui_img_587468927);    // assets/Btn-small-on-100.png
LV_IMG_DECLARE(ui_img_menubtn1_png);    // assets/MenuBtn1.png
LV_IMG_DECLARE(ui_img_1891462800);    // assets/silver-bezel-free-120.png
LV_IMG_DECLARE(ui_img_410295087);    // assets/switch-50.png
LV_IMG_DECLARE(ui_img_1640860301);    // assets/kipp-1-off-70.png
LV_IMG_DECLARE(ui_img_888658411);    // assets/kipp-1-on-70.png
LV_IMG_DECLARE(ui_img_743505413);    // assets/kipp-1-neutral-70.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
