// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _JEEPIFY_UI_COMP_HOOK_H
#define _JEEPIFY_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_ButtonSensorSmall_create_hook(lv_obj_t * comp);
void ui_comp_ButtonSwitchSmall_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
