// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_comp_ImgButtonSwitchSmall_create_hook(lv_obj_t * comp)
{
}

void ui_comp_PnlMulti_compedit_create_hook(lv_obj_t * comp)
{
}

void ui_comp_PnlMulti_create_hook(lv_obj_t * comp)
{
}

void ui_comp_BtnSensSmall_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ButtonSwitchSmall_create_hook(lv_obj_t * comp)
{
}

void ui_comp_BtnSensSmall_compedit_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ButtonSensorSmall_create_hook(lv_obj_t * comp)
{
}
