// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _UI_COMP_BUTTONSWITCHSMALL_H
#define _UI_COMP_BUTTONSWITCHSMALL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonSwitchSmall
#define UI_COMP_BUTTONSWITCHSMALL_BUTTONSWITCHSMALL 0
#define UI_COMP_BUTTONSWITCHSMALL_LBLPEER 1
#define UI_COMP_BUTTONSWITCHSMALL_LBLPERIPH 2
#define UI_COMP_BUTTONSWITCHSMALL_LBLVALUE 3
#define UI_COMP_BUTTONSWITCHSMALL_LBLPOSITION 4
#define _UI_COMP_BUTTONSWITCHSMALL_NUM 5
lv_obj_t * ui_ButtonSwitchSmall_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
