// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScrSwitch_screen_init(void)
{
    ui_ScrSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrSwitch, &ui_img_btn_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSwitchPeer = lv_label_create(ui_ScrSwitch);
    lv_obj_set_width(ui_LblSwitchPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSwitchPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSwitchPeer, 0);
    lv_obj_set_y(ui_LblSwitchPeer, 35);
    lv_obj_set_align(ui_LblSwitchPeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSwitchPeer, "Peer");
    lv_obj_set_style_text_color(ui_LblSwitchPeer, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSwitchPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSwitchPeer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSwitchPeriph = lv_label_create(ui_ScrSwitch);
    lv_obj_set_width(ui_LblSwitchPeriph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSwitchPeriph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSwitchPeriph, 0);
    lv_obj_set_y(ui_LblSwitchPeriph, -20);
    lv_obj_set_align(ui_LblSwitchPeriph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSwitchPeriph, "Periph");
    lv_obj_set_style_text_color(ui_LblSwitchPeriph, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSwitchPeriph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSwitchPeriph, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrSwitch, ui_event_ScrSwitch, LV_EVENT_ALL, NULL);

}
