// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScrSwitch_screen_init(void)
{
    ui_ScrSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrSwitch, &ui_img_1464630232, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScrSwitch, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSwitchPeer = lv_label_create(ui_ScrSwitch);
    lv_obj_set_width(ui_LblSwitchPeer, 120);
    lv_obj_set_height(ui_LblSwitchPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSwitchPeer, 2);
    lv_obj_set_y(ui_LblSwitchPeer, 140);
    lv_obj_set_align(ui_LblSwitchPeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSwitchPeer, "Peer");
    lv_obj_add_flag(ui_LblSwitchPeer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_align(ui_LblSwitchPeer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSwitchPeer, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblSwitchPeer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BtnBg);
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BtnBg);
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_BtnBorder);
    ui_object_set_themeable_style_property(ui_LblSwitchPeer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_BtnBorder);
    lv_obj_set_style_border_width(ui_LblSwitchPeer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblSwitchPeer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblSwitchPeer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblSwitchPeer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblSwitchPeer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSwitchNext = lv_btn_create(ui_ScrSwitch);
    lv_obj_set_width(ui_BtnSwitchNext, 50);
    lv_obj_set_height(ui_BtnSwitchNext, 50);
    lv_obj_set_x(ui_BtnSwitchNext, 207);
    lv_obj_set_y(ui_BtnSwitchNext, -130);
    lv_obj_set_align(ui_BtnSwitchNext, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BtnSwitchNext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BtnSwitchNext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BtnBg);
    ui_object_set_themeable_style_property(ui_BtnSwitchNext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BtnBg);
    lv_obj_set_style_bg_img_src(ui_BtnSwitchNext, &ui_img_315456014, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BtnSwitchNext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_BtnBorder);
    ui_object_set_themeable_style_property(ui_BtnSwitchNext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_BtnBorder);
    lv_obj_set_style_border_width(ui_BtnSwitchNext, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSwitchLast = lv_btn_create(ui_ScrSwitch);
    lv_obj_set_width(ui_BtnSwitchLast, 50);
    lv_obj_set_height(ui_BtnSwitchLast, 50);
    lv_obj_set_x(ui_BtnSwitchLast, 206);
    lv_obj_set_y(ui_BtnSwitchLast, 130);
    lv_obj_set_align(ui_BtnSwitchLast, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BtnSwitchLast, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BtnSwitchLast, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BtnBg);
    ui_object_set_themeable_style_property(ui_BtnSwitchLast, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BtnBg);
    lv_obj_set_style_bg_img_src(ui_BtnSwitchLast, &ui_img_694597045, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BtnSwitchLast, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_BtnBorder);
    ui_object_set_themeable_style_property(ui_BtnSwitchLast, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_BtnBorder);
    lv_obj_set_style_border_width(ui_BtnSwitchLast, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnSwitchNext, ui_event_BtnSwitchNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSwitchLast, ui_event_BtnSwitchLast, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrSwitch, ui_event_ScrSwitch, LV_EVENT_ALL, NULL);

}
